version: '3.5'

services:
    db:
        image: postgres:latest
        hostname: db
        environment:
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: rinha
        ports:
            - '5432:5432'
        volumes:
            - ./init.sql:/docker-entrypoint-initdb.d/init.sql
        deploy:
            resources:
                limits:
                    cpus: '0.8'
                    memory: '1.5GB'

    api1: &api
        build: .
        hostname: api1
        depends_on:
            - db
        environment:
            - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=rinha;Username=postgres;Password=postgres;
        ports:
            - '3000:80'   
        deploy:
            resources:
                limits:
                    cpus: '0.25'
                    memory: '0.5GB'

    api2:
        <<: *api
        hostname: api2
        ports:
            - '3001:80'